# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'polkitex.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PolkitExplorer(object):
    def setupUi(self, PolkitExplorer):
        PolkitExplorer.setObjectName("PolkitExplorer")
        PolkitExplorer.setWindowModality(QtCore.Qt.ApplicationModal)
        PolkitExplorer.resize(1024, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(PolkitExplorer.sizePolicy().hasHeightForWidth())
        PolkitExplorer.setSizePolicy(sizePolicy)
        PolkitExplorer.setMinimumSize(QtCore.QSize(1024, 350))
        PolkitExplorer.setMaximumSize(QtCore.QSize(1920, 1080))
        PolkitExplorer.setSizeIncrement(QtCore.QSize(32, 32))
        PolkitExplorer.setBaseSize(QtCore.QSize(1024, 350))
        PolkitExplorer.setStatusTip("")
        PolkitExplorer.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(PolkitExplorer)
        self.centralwidget.setObjectName("centralwidget")
        self.polkitActionDescription = QtWidgets.QLabel(self.centralwidget)
        self.polkitActionDescription.setGeometry(QtCore.QRect(130, 140, 731, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.polkitActionDescription.setFont(font)
        self.polkitActionDescription.setAutoFillBackground(True)
        self.polkitActionDescription.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.polkitActionDescription.setText("")
        self.polkitActionDescription.setTextFormat(QtCore.Qt.PlainText)
        self.polkitActionDescription.setScaledContents(True)
        self.polkitActionDescription.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.polkitActionDescription.setObjectName("polkitActionDescription")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 190, 641, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.currentallowanylabel = QtWidgets.QLabel(self.frame)
        self.currentallowanylabel.setGeometry(QtCore.QRect(30, 20, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.currentallowanylabel.setFont(font)
        self.currentallowanylabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.currentallowanylabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.currentallowanylabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.currentallowanylabel.setObjectName("currentallowanylabel")
        self.currentallowanylabel_2 = QtWidgets.QLabel(self.frame)
        self.currentallowanylabel_2.setGeometry(QtCore.QRect(220, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.currentallowanylabel_2.setFont(font)
        self.currentallowanylabel_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.currentallowanylabel_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.currentallowanylabel_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.currentallowanylabel_2.setObjectName("currentallowanylabel_2")
        self.currentallowanylabel_3 = QtWidgets.QLabel(self.frame)
        self.currentallowanylabel_3.setGeometry(QtCore.QRect(440, 20, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.currentallowanylabel_3.setFont(font)
        self.currentallowanylabel_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.currentallowanylabel_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.currentallowanylabel_3.setLineWidth(1)
        self.currentallowanylabel_3.setMidLineWidth(0)
        self.currentallowanylabel_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.currentallowanylabel_3.setObjectName("currentallowanylabel_3")
        self.allowAnyEdit = QtWidgets.QComboBox(self.frame)
        self.allowAnyEdit.setGeometry(QtCore.QRect(20, 60, 151, 29))
        self.allowAnyEdit.setEditable(False)
        self.allowAnyEdit.setObjectName("allowAnyEdit")
        self.allowInactiveEdit = QtWidgets.QComboBox(self.frame)
        self.allowInactiveEdit.setGeometry(QtCore.QRect(210, 60, 181, 29))
        self.allowInactiveEdit.setEditable(False)
        self.allowInactiveEdit.setMaxVisibleItems(10)
        self.allowInactiveEdit.setModelColumn(0)
        self.allowInactiveEdit.setObjectName("allowInactiveEdit")
        self.allowActiveEdit = QtWidgets.QComboBox(self.frame)
        self.allowActiveEdit.setGeometry(QtCore.QRect(420, 60, 191, 29))
        self.allowActiveEdit.setEditable(False)
        self.allowActiveEdit.setMinimumContentsLength(0)
        self.allowActiveEdit.setModelColumn(0)
        self.allowActiveEdit.setObjectName("allowActiveEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setIndent(4)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 1001, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setIndent(4)
        self.label.setObjectName("label")
        self.policyKitFileName = QtWidgets.QLabel(self.centralwidget)
        self.policyKitFileName.setGeometry(QtCore.QRect(130, 20, 731, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.policyKitFileName.setFont(font)
        self.policyKitFileName.setAutoFillBackground(True)
        self.policyKitFileName.setStyleSheet("")
        self.policyKitFileName.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.policyKitFileName.setFrameShadow(QtWidgets.QFrame.Plain)
        self.policyKitFileName.setLineWidth(2)
        self.policyKitFileName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.policyKitFileName.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.policyKitFileName.setObjectName("policyKitFileName")
        self.actionComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.actionComboBox.setGeometry(QtCore.QRect(130, 90, 731, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.actionComboBox.setFont(font)
        self.actionComboBox.setObjectName("actionComboBox")
        self.polkitActionNameLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.polkitActionNameLabel_2.setEnabled(True)
        self.polkitActionNameLabel_2.setGeometry(QtCore.QRect(10, 190, 1001, 108))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.polkitActionNameLabel_2.sizePolicy().hasHeightForWidth())
        self.polkitActionNameLabel_2.setSizePolicy(sizePolicy)
        self.polkitActionNameLabel_2.setSizeIncrement(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.polkitActionNameLabel_2.setFont(font)
        self.polkitActionNameLabel_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.polkitActionNameLabel_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.polkitActionNameLabel_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.polkitActionNameLabel_2.setMidLineWidth(0)
        self.polkitActionNameLabel_2.setScaledContents(False)
        self.polkitActionNameLabel_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.polkitActionNameLabel_2.setIndent(4)
        self.polkitActionNameLabel_2.setObjectName("polkitActionNameLabel_2")
        self.actionsCounterDisplay = QtWidgets.QLCDNumber(self.centralwidget)
        self.actionsCounterDisplay.setGeometry(QtCore.QRect(870, 110, 131, 61))
        self.actionsCounterDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.actionsCounterDisplay.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.actionsCounterDisplay.setObjectName("actionsCounterDisplay")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(870, 90, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.saveBnt = QtWidgets.QPushButton(self.centralwidget)
        self.saveBnt.setGeometry(QtCore.QRect(910, 250, 86, 29))
        self.saveBnt.setObjectName("saveBnt")
        self.cancelBnt = QtWidgets.QPushButton(self.centralwidget)
        self.cancelBnt.setGeometry(QtCore.QRect(810, 250, 86, 29))
        self.cancelBnt.setObjectName("cancelBnt")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setIndent(4)
        self.label_4.setObjectName("label_4")
        self.openBnt = QtWidgets.QPushButton(self.centralwidget)
        self.openBnt.setGeometry(QtCore.QRect(870, 20, 131, 41))
        self.openBnt.setObjectName("openBnt")
        self.polkitActionNameLabel_2.raise_()
        self.frame.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.policyKitFileName.raise_()
        self.actionsCounterDisplay.raise_()
        self.actionComboBox.raise_()
        self.polkitActionDescription.raise_()
        self.saveBnt.raise_()
        self.cancelBnt.raise_()
        self.label_4.raise_()
        self.openBnt.raise_()
        PolkitExplorer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PolkitExplorer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.menuHelp.setFont(font)
        self.menuHelp.setObjectName("menuHelp")
        PolkitExplorer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PolkitExplorer)
        self.statusbar.setObjectName("statusbar")
        PolkitExplorer.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(PolkitExplorer)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.actionOpen.setFont(font)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAbout = QtWidgets.QAction(PolkitExplorer)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(PolkitExplorer)
        self.actionQuit.setObjectName("actionQuit")
        self.actionShow_Glossary = QtWidgets.QAction(PolkitExplorer)
        self.actionShow_Glossary.setObjectName("actionShow_Glossary")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionShow_Glossary)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(PolkitExplorer)
        self.allowAnyEdit.setCurrentIndex(-1)
        self.allowActiveEdit.setCurrentIndex(-1)
        self.actionComboBox.currentIndexChanged['int'].connect(PolkitExplorer.actionComboBoxChanged)
        self.actionOpen.triggered.connect(PolkitExplorer.fileOpen)
        self.actionQuit.triggered.connect(PolkitExplorer.fileQuit)
        self.actionAbout.triggered.connect(PolkitExplorer.fileAbout)
        self.actionShow_Glossary.triggered.connect(PolkitExplorer.helpGlossary)
        self.allowActiveEdit.activated['int'].connect(PolkitExplorer.onPolicyChanged)
        self.allowInactiveEdit.activated['int'].connect(PolkitExplorer.onPolicyChanged)
        self.allowAnyEdit.activated['int'].connect(PolkitExplorer.onPolicyChanged)
        self.openBnt.clicked.connect(PolkitExplorer.fileOpen)
        QtCore.QMetaObject.connectSlotsByName(PolkitExplorer)

    def retranslateUi(self, PolkitExplorer):
        _translate = QtCore.QCoreApplication.translate
        PolkitExplorer.setWindowTitle(_translate("PolkitExplorer", "Polkit Admin"))
        self.polkitActionDescription.setToolTip(_translate("PolkitExplorer", "<html><head/><body><p>The Description of the Action as entered in the Policy file loaded. If no description is found this will tell you that fact.</p></body></html>"))
        self.currentallowanylabel.setToolTip(_translate("PolkitExplorer", "<html><head/><body><p>If set to &quot;yes&quot; will give any user permission to perform the action as described in the Description above. </p></body></html>"))
        self.currentallowanylabel.setText(_translate("PolkitExplorer", "Allow Any"))
        self.currentallowanylabel_2.setToolTip(_translate("PolkitExplorer", "<html><head/><body><p>&quot;Inactive&quot; users are ones who are not directly logged into the system\'s console. This includes anyone who is logged in remotely, whether it be via ssh, telnet, or even RDP.</p></body></html>"))
        self.currentallowanylabel_2.setText(_translate("PolkitExplorer", "Allow Inactive"))
        self.currentallowanylabel_3.setToolTip(_translate("PolkitExplorer", "<html><head/><body><p>&quot;Active&quot; users are ones who are directly logged into a system\'s console, via a locally connected terminal. Users directly logged into a GUI at the system console, for example.</p></body></html>"))
        self.currentallowanylabel_3.setText(_translate("PolkitExplorer", "Allow Active"))
        self.label_3.setText(_translate("PolkitExplorer", "Description"))
        self.label.setText(_translate("PolkitExplorer", "Current Policy"))
        self.policyKitFileName.setToolTip(_translate("PolkitExplorer", "<html><head/><body><p>The full pathname of the currently opened Polkit policy file.</p></body></html>"))
        self.policyKitFileName.setText(_translate("PolkitExplorer", "Please open a policy file..."))
        self.actionComboBox.setToolTip(_translate("PolkitExplorer", "<html><head/><body><p><span style=\" font-weight:600;\">Drop-down list of all the actions within the policy file. Clicking on this will display the drop-down list, or you can use your scrollwheel to browse through them, too.</span></p></body></html>"))
        self.polkitActionNameLabel_2.setText(_translate("PolkitExplorer", "Policy Settings"))
        self.actionsCounterDisplay.setToolTip(_translate("PolkitExplorer", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Displays the number of Actions within a Polkit policy file.</span></p></body></html>"))
        self.label_2.setText(_translate("PolkitExplorer", "# Actions"))
        self.saveBnt.setText(_translate("PolkitExplorer", "Save"))
        self.cancelBnt.setText(_translate("PolkitExplorer", "Reset"))
        self.label_4.setText(_translate("PolkitExplorer", "Action"))
        self.openBnt.setText(_translate("PolkitExplorer", "Open"))
        self.menuFile.setTitle(_translate("PolkitExplorer", "&File"))
        self.menuHelp.setTitle(_translate("PolkitExplorer", "&Help"))
        self.actionOpen.setText(_translate("PolkitExplorer", "&Open"))
        self.actionAbout.setText(_translate("PolkitExplorer", "&About"))
        self.actionQuit.setText(_translate("PolkitExplorer", "&Quit"))
        self.actionShow_Glossary.setText(_translate("PolkitExplorer", "&Show Glossary"))

