# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'polkitex.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PolkitAdmin(object):
    def setupUi(self, PolkitAdmin):
        PolkitAdmin.setObjectName("PolkitAdmin")
        PolkitAdmin.resize(1025, 320)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PolkitAdmin.sizePolicy().hasHeightForWidth())
        PolkitAdmin.setSizePolicy(sizePolicy)
        PolkitAdmin.setMinimumSize(QtCore.QSize(1025, 320))
        PolkitAdmin.setMaximumSize(QtCore.QSize(1025, 320))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        PolkitAdmin.setFont(font)
        PolkitAdmin.setFocusPolicy(QtCore.Qt.ClickFocus)
        PolkitAdmin.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        PolkitAdmin.setStatusTip("")
        PolkitAdmin.setAutoFillBackground(False)
        PolkitAdmin.setStyleSheet("")
        PolkitAdmin.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        PolkitAdmin.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(PolkitAdmin)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.aframe = QtWidgets.QFrame(self.centralwidget)
        self.aframe.setGeometry(QtCore.QRect(10, 10, 1000, 42))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aframe.sizePolicy().hasHeightForWidth())
        self.aframe.setSizePolicy(sizePolicy)
        self.aframe.setMinimumSize(QtCore.QSize(0, 32))
        self.aframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.aframe.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.aframe.setLineWidth(0)
        self.aframe.setMidLineWidth(0)
        self.aframe.setObjectName("aframe")
        self.currentPolicy = QtWidgets.QHBoxLayout(self.aframe)
        self.currentPolicy.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.currentPolicy.setContentsMargins(2, 0, 2, 0)
        self.currentPolicy.setSpacing(2)
        self.currentPolicy.setObjectName("currentPolicy")
        self.label = QtWidgets.QLabel(self.aframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(115, 36))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(0)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.currentPolicy.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.currentPolicy.addItem(spacerItem)
        self.policyKitFileName = QtWidgets.QLabel(self.aframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.policyKitFileName.sizePolicy().hasHeightForWidth())
        self.policyKitFileName.setSizePolicy(sizePolicy)
        self.policyKitFileName.setMinimumSize(QtCore.QSize(777, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.policyKitFileName.setFont(font)
        self.policyKitFileName.setAutoFillBackground(False)
        self.policyKitFileName.setStyleSheet("")
        self.policyKitFileName.setFrameShape(QtWidgets.QFrame.Panel)
        self.policyKitFileName.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.policyKitFileName.setLineWidth(1)
        self.policyKitFileName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.policyKitFileName.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.policyKitFileName.setObjectName("policyKitFileName")
        self.currentPolicy.addWidget(self.policyKitFileName)
        spacerItem1 = QtWidgets.QSpacerItem(12, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.currentPolicy.addItem(spacerItem1)
        self.openBnt = QtWidgets.QPushButton(self.aframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openBnt.sizePolicy().hasHeightForWidth())
        self.openBnt.setSizePolicy(sizePolicy)
        self.openBnt.setMinimumSize(QtCore.QSize(80, 40))
        self.openBnt.setObjectName("openBnt")
        self.currentPolicy.addWidget(self.openBnt)
        spacerItem2 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.currentPolicy.addItem(spacerItem2)
        self.currentPolicy.setStretch(2, 1)
        self.cframe = QtWidgets.QFrame(self.centralwidget)
        self.cframe.setGeometry(QtCore.QRect(10, 140, 1000, 42))
        self.cframe.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cframe.setLineWidth(0)
        self.cframe.setObjectName("cframe")
        self.descriptionBar = QtWidgets.QHBoxLayout(self.cframe)
        self.descriptionBar.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.descriptionBar.setContentsMargins(2, 0, 2, 0)
        self.descriptionBar.setSpacing(2)
        self.descriptionBar.setObjectName("descriptionBar")
        self.polkitActionLabel = QtWidgets.QLabel(self.cframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polkitActionLabel.sizePolicy().hasHeightForWidth())
        self.polkitActionLabel.setSizePolicy(sizePolicy)
        self.polkitActionLabel.setMinimumSize(QtCore.QSize(115, 36))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.polkitActionLabel.setFont(font)
        self.polkitActionLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.polkitActionLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.polkitActionLabel.setLineWidth(0)
        self.polkitActionLabel.setMidLineWidth(0)
        self.polkitActionLabel.setScaledContents(False)
        self.polkitActionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.polkitActionLabel.setIndent(16)
        self.polkitActionLabel.setObjectName("polkitActionLabel")
        self.descriptionBar.addWidget(self.polkitActionLabel)
        spacerItem3 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.descriptionBar.addItem(spacerItem3)
        self.polkitActionDescription = QtWidgets.QLabel(self.cframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polkitActionDescription.sizePolicy().hasHeightForWidth())
        self.polkitActionDescription.setSizePolicy(sizePolicy)
        self.polkitActionDescription.setMinimumSize(QtCore.QSize(69, 32))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.polkitActionDescription.setFont(font)
        self.polkitActionDescription.setAutoFillBackground(False)
        self.polkitActionDescription.setFrameShape(QtWidgets.QFrame.Panel)
        self.polkitActionDescription.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.polkitActionDescription.setText("")
        self.polkitActionDescription.setTextFormat(QtCore.Qt.PlainText)
        self.polkitActionDescription.setScaledContents(True)
        self.polkitActionDescription.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.polkitActionDescription.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.polkitActionDescription.setObjectName("polkitActionDescription")
        self.descriptionBar.addWidget(self.polkitActionDescription)
        self.bframe = QtWidgets.QFrame(self.centralwidget)
        self.bframe.setGeometry(QtCore.QRect(10, 70, 1001, 54))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bframe.sizePolicy().hasHeightForWidth())
        self.bframe.setSizePolicy(sizePolicy)
        self.bframe.setMinimumSize(QtCore.QSize(0, 32))
        self.bframe.setAutoFillBackground(False)
        self.bframe.setStyleSheet("")
        self.bframe.setFrameShape(QtWidgets.QFrame.Panel)
        self.bframe.setFrameShadow(QtWidgets.QFrame.Plain)
        self.bframe.setLineWidth(0)
        self.bframe.setObjectName("bframe")
        self.actionBar = QtWidgets.QHBoxLayout(self.bframe)
        self.actionBar.setContentsMargins(2, 0, 2, 0)
        self.actionBar.setSpacing(2)
        self.actionBar.setObjectName("actionBar")
        self.actionSelLabel = QtWidgets.QLabel(self.bframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionSelLabel.sizePolicy().hasHeightForWidth())
        self.actionSelLabel.setSizePolicy(sizePolicy)
        self.actionSelLabel.setMinimumSize(QtCore.QSize(115, 32))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.actionSelLabel.setFont(font)
        self.actionSelLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.actionSelLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.actionSelLabel.setLineWidth(0)
        self.actionSelLabel.setScaledContents(False)
        self.actionSelLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.actionSelLabel.setIndent(16)
        self.actionSelLabel.setObjectName("actionSelLabel")
        self.actionBar.addWidget(self.actionSelLabel)
        spacerItem4 = QtWidgets.QSpacerItem(8, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.actionBar.addItem(spacerItem4)
        self.frame_2 = QtWidgets.QFrame(self.bframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(777, 32))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.actionComboBox = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionComboBox.sizePolicy().hasHeightForWidth())
        self.actionComboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.actionComboBox.setFont(font)
        self.actionComboBox.setAutoFillBackground(True)
        self.actionComboBox.setStyleSheet("")
        self.actionComboBox.setFrame(True)
        self.actionComboBox.setObjectName("actionComboBox")
        self.horizontalLayout.addWidget(self.actionComboBox)
        self.actionBar.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 200, 1001, 97))
        self.frame.setStyleSheet("#frame {\n"
"    border-top: 2px dotted rgb(211, 215, 207);\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.policyEditor = QtWidgets.QGridLayout(self.frame)
        self.policyEditor.setContentsMargins(0, 0, 0, 0)
        self.policyEditor.setSpacing(0)
        self.policyEditor.setObjectName("policyEditor")
        spacerItem5 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.policyEditor.addItem(spacerItem5, 3, 1, 1, 1)
        self.saveBnt = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveBnt.sizePolicy().hasHeightForWidth())
        self.saveBnt.setSizePolicy(sizePolicy)
        self.saveBnt.setMinimumSize(QtCore.QSize(0, 40))
        self.saveBnt.setDefault(True)
        self.saveBnt.setFlat(False)
        self.saveBnt.setObjectName("saveBnt")
        self.policyEditor.addWidget(self.saveBnt, 3, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.policyEditor.addItem(spacerItem6, 3, 3, 1, 1)
        self.policySelector = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.policySelector.sizePolicy().hasHeightForWidth())
        self.policySelector.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.policySelector.setFont(font)
        self.policySelector.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.policySelector.setFrameShadow(QtWidgets.QFrame.Plain)
        self.policySelector.setLineWidth(0)
        self.policySelector.setMidLineWidth(0)
        self.policySelector.setObjectName("policySelector")
        self.gridLayout = QtWidgets.QGridLayout(self.policySelector)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(8)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.activeBox = QtWidgets.QFrame(self.policySelector)
        self.activeBox.setStyleSheet("")
        self.activeBox.setFrameShape(QtWidgets.QFrame.Panel)
        self.activeBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.activeBox.setObjectName("activeBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.activeBox)
        self.verticalLayout.setContentsMargins(18, 18, 18, 18)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.allowactive = QtWidgets.QLabel(self.activeBox)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.allowactive.setFont(font)
        self.allowactive.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.allowactive.setFrameShadow(QtWidgets.QFrame.Plain)
        self.allowactive.setLineWidth(1)
        self.allowactive.setMidLineWidth(0)
        self.allowactive.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.allowactive.setObjectName("allowactive")
        self.verticalLayout.addWidget(self.allowactive)
        self.allowActiveEdit = QtWidgets.QComboBox(self.activeBox)
        self.allowActiveEdit.setEditable(False)
        self.allowActiveEdit.setMinimumContentsLength(0)
        self.allowActiveEdit.setModelColumn(0)
        self.allowActiveEdit.setObjectName("allowActiveEdit")
        self.verticalLayout.addWidget(self.allowActiveEdit)
        self.gridLayout.addWidget(self.activeBox, 0, 3, 1, 1)
        self.anyBox = QtWidgets.QFrame(self.policySelector)
        self.anyBox.setStyleSheet("")
        self.anyBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.anyBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.anyBox.setObjectName("anyBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.anyBox)
        self.verticalLayout_3.setContentsMargins(18, 18, 18, 18)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.allowanylabel = QtWidgets.QLabel(self.anyBox)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.allowanylabel.setFont(font)
        self.allowanylabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.allowanylabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.allowanylabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.allowanylabel.setObjectName("allowanylabel")
        self.verticalLayout_3.addWidget(self.allowanylabel)
        self.allowAnyEdit = QtWidgets.QComboBox(self.anyBox)
        self.allowAnyEdit.setEditable(False)
        self.allowAnyEdit.setObjectName("allowAnyEdit")
        self.verticalLayout_3.addWidget(self.allowAnyEdit)
        self.gridLayout.addWidget(self.anyBox, 0, 0, 1, 1)
        self.inactiveBox = QtWidgets.QFrame(self.policySelector)
        self.inactiveBox.setFrameShape(QtWidgets.QFrame.Panel)
        self.inactiveBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.inactiveBox.setObjectName("inactiveBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.inactiveBox)
        self.verticalLayout_2.setContentsMargins(18, 18, 18, 18)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.allowinactivatelabel = QtWidgets.QLabel(self.inactiveBox)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.allowinactivatelabel.setFont(font)
        self.allowinactivatelabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.allowinactivatelabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.allowinactivatelabel.setLineWidth(0)
        self.allowinactivatelabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.allowinactivatelabel.setObjectName("allowinactivatelabel")
        self.verticalLayout_2.addWidget(self.allowinactivatelabel)
        self.allowInactiveEdit = QtWidgets.QComboBox(self.inactiveBox)
        self.allowInactiveEdit.setEditable(False)
        self.allowInactiveEdit.setMaxVisibleItems(10)
        self.allowInactiveEdit.setModelColumn(0)
        self.allowInactiveEdit.setObjectName("allowInactiveEdit")
        self.verticalLayout_2.addWidget(self.allowInactiveEdit)
        self.gridLayout.addWidget(self.inactiveBox, 0, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.policySelector)
        self.line_2.setStyleSheet("Line {\n"
"    border 2px solid;\n"
"}")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 2, 1, 1)
        self.policyEditor.addWidget(self.policySelector, 0, 0, 4, 1)
        self.cancelBnt = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelBnt.sizePolicy().hasHeightForWidth())
        self.cancelBnt.setSizePolicy(sizePolicy)
        self.cancelBnt.setMinimumSize(QtCore.QSize(0, 40))
        self.cancelBnt.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.cancelBnt.setAcceptDrops(False)
        self.cancelBnt.setToolTipDuration(-1)
        self.cancelBnt.setObjectName("cancelBnt")
        self.policyEditor.addWidget(self.cancelBnt, 1, 2, 1, 1)
        self.cframe.raise_()
        self.bframe.raise_()
        self.frame.raise_()
        self.aframe.raise_()
        PolkitAdmin.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(PolkitAdmin)
        self.statusBar.setStatusTip("")
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName("statusBar")
        PolkitAdmin.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(PolkitAdmin)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.actionOpen.setFont(font)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAbout = QtWidgets.QAction(PolkitAdmin)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.actionAbout.setFont(font)
        self.actionAbout.setObjectName("actionAbout")
        self.actionQuit = QtWidgets.QAction(PolkitAdmin)
        self.actionQuit.setObjectName("actionQuit")
        self.actionShow_Glossary = QtWidgets.QAction(PolkitAdmin)
        self.actionShow_Glossary.setObjectName("actionShow_Glossary")

        self.retranslateUi(PolkitAdmin)
        self.allowActiveEdit.setCurrentIndex(-1)
        self.allowAnyEdit.setCurrentIndex(-1)
        self.openBnt.clicked.connect(PolkitAdmin.fileOpen)
        self.actionQuit.triggered.connect(PolkitAdmin.fileQuit)
        self.actionAbout.triggered.connect(PolkitAdmin.fileAbout)
        self.actionShow_Glossary.triggered.connect(PolkitAdmin.helpGlossary)
        self.actionComboBox.currentIndexChanged['int'].connect(PolkitAdmin.actionComboBoxChanged)
        self.saveBnt.clicked.connect(PolkitAdmin.fileSave)
        QtCore.QMetaObject.connectSlotsByName(PolkitAdmin)

    def retranslateUi(self, PolkitAdmin):
        _translate = QtCore.QCoreApplication.translate
        PolkitAdmin.setWindowTitle(_translate("PolkitAdmin", "Polkit Admin"))
        self.label.setText(_translate("PolkitAdmin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:4px; -qt-block-indent:0; text-indent:0px;\">Current Policy</p></body></html>"))
        self.policyKitFileName.setToolTip(_translate("PolkitAdmin", "<html><head/><body><p>The full pathname of the currently opened Polkit policy file.</p></body></html>"))
        self.policyKitFileName.setText(_translate("PolkitAdmin", "<html><head/><body><p>Please open a policy file...</p></body></html>"))
        self.openBnt.setText(_translate("PolkitAdmin", "Open"))
        self.polkitActionLabel.setText(_translate("PolkitAdmin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:4px; -qt-block-indent:0; text-indent:0px;\">Description</p></body></html>"))
        self.polkitActionDescription.setToolTip(_translate("PolkitAdmin", "<html><head/><body><p>The Description of the Action as entered in the Policy file loaded. If no description is found this will tell you that fact.</p></body></html>"))
        self.actionSelLabel.setText(_translate("PolkitAdmin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:4px; -qt-block-indent:0; text-indent:0px;\">Action</p></body></html>"))
        self.actionComboBox.setToolTip(_translate("PolkitAdmin", "<html><head/><body><p><span style=\" font-weight:600;\">Drop-down list of all the actions within the policy file. Clicking on this will display the drop-down list, or you can use your scrollwheel to browse through them, too.</span></p></body></html>"))
        self.saveBnt.setText(_translate("PolkitAdmin", "Save"))
        self.allowactive.setToolTip(_translate("PolkitAdmin", "<html><head/><body><p>&quot;Active&quot; users are ones who are directly logged into a system\'s console, via a locally connected terminal. Users directly logged into a GUI at the system console, for example.</p></body></html>"))
        self.allowactive.setText(_translate("PolkitAdmin", "Allow Active"))
        self.allowanylabel.setToolTip(_translate("PolkitAdmin", "<html><head/><body><p>If set to &quot;yes&quot; will give any user permission to perform the action as described in the Description above. </p></body></html>"))
        self.allowanylabel.setText(_translate("PolkitAdmin", "Allow Any"))
        self.allowinactivatelabel.setToolTip(_translate("PolkitAdmin", "<html><head/><body><p>&quot;Inactive&quot; users are ones who are not directly logged into the system\'s console. This includes anyone who is logged in remotely, whether it be via ssh, telnet, or even RDP.</p></body></html>"))
        self.allowinactivatelabel.setText(_translate("PolkitAdmin", "Allow Inactive"))
        self.cancelBnt.setText(_translate("PolkitAdmin", "Reset"))
        self.actionOpen.setText(_translate("PolkitAdmin", "&Open"))
        self.actionAbout.setText(_translate("PolkitAdmin", "&About"))
        self.actionQuit.setText(_translate("PolkitAdmin", "&Quit"))
        self.actionShow_Glossary.setText(_translate("PolkitAdmin", "&Show Glossary"))

